# Generated by Django 4.2.1 on 2024-10-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
