# Generated by Django 4.2.1 on 2024-10-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0003_alter_note_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("deleted_text", models.BooleanField(default=False)),
            ],
        ),
    ]
