# Generated by Django 4.2.1 on 2024-10-03 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0004_verb"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Verb",
        ),
    ]
