# Generated by Django 4.2.1 on 2024-10-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0007_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_verb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
