# Generated by Django 4.2.1 on 2024-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0008_alter_note_content_alter_post_content_verb"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="verb_simple_second_step",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
