# Generated by Django 4.2.1 on 2024-10-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0010_post_verb_simple_second_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="subject",
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
