# Generated by Django 4.2.1 on 2024-10-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0011_post_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
