# Generated by Django 4.2.1 on 2024-10-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0012_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text_mafool",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
