# Generated by Django 4.2.1 on 2024-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0013_post_text_mafool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.TextField()),
                ("y", models.TextField()),
                ("z", models.TextField()),
                ("m", models.TextField()),
            ],
        ),
    ]
