# Generated by Django 4.2.1 on 2024-10-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0014_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pre_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
