# Generated by Django 4.2.1 on 2024-10-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PVSP", "0015_post_pre_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="adverb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="pre_adverb",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
